Custom ACRE Signal Calculation
LAMBS-Nopryl/LMF.VR pull request #5
Opened 2018-12-04 22:21 UTC by diwako

This adds a custom signal calculation to every player. it will do nothing on its own, but it allows to boost receiving and/or sending power mid mission if there are radio problems.

Here is a demonstration;
[![Video](https://img.youtube.com/vi/WaptoFbkOwY/0.jpg)](https://www.youtube.com/watch?v=WaptoFbkOwY)

It also adds a bit of ~~log spam~~ debug so it is possible to take a look in the players RPT file if there might be something wrong.

Example:
To boost signal strength mid mission an admin just executes this _globally_ into debug console
```sqf
player setVariable ["acre_send_power",2,true];
player setVariable ["acre_receive_power",2,true];
```
This will boost receiving and sending times 2. Of course any number ranging from 0 to 99999999999 could be used. (This also enables signal jamming hint hint)

2018-12-07 10:13 UTC, G3rrus requested changes

2018-12-07 10:13 UTC, G3rrus commented on framework/player/init/acreSignalCalc.sqf
> +if(!hasInterface) exitWith {};
I just see minor things with it, would move the ! outside of the brackets to fit how its done in the rest of the framework + maybe move your name as the maker from the title to the description (again to fit the rest of the framework)

2018-12-09 00:40 UTC, Alextwokay commented
Could this perhaps be better off as a mod, and not the mission framework?
Not all missions we play use LMF.

2018-12-10 07:18 UTC, diwako commented
> Could this perhaps be better off as a mod, and not the mission framework?
> Not all missions we play use LMF.

That is fine by me, please decide this in your next meeting. Be also aware that this will probably not fix the current issues as it seems to stem from something else.

2018-12-10 19:03 UTC, Liquidtracer commented
Yup, we're diving deeper into RPT's and such leaning more towards acre/arma installs passing bad data to others causing more issues. Just confirming that is something that we ourselves aren't causing before submitting a bug report/ticket to acre devs.

We might end up not having to merge this in at all. But its good to have a backup plan.

2018-12-15 12:15 UTC, G3rrus commented
So am I right with the assumption that even if we need this its going into a mod and not into the framework?

2019-01-17 12:23 UTC, closed without merging